name: test and deploy
on: push 
jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: setup node
              uses: actions/setup-node@v3
              with: 
                node-version: 18
                
            - name: install dependencies
              run: npm install 

            - name: setup Mongodb
              uses: supercharge/mongodb-github-action@1.10.0
              with:
                mongodb-version: 6
            - name: run tests 
              run: |
                npm run start:test &
                npm test 